logging:
  config: classpath:log4j2-spring-@profileActive@.xml
  file:
    path: .
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ${rootArtifactId}
  profiles:
    active: @profileActive@
  datasource:
    dynamic:
      primary: mysql
      strict: true
      datasource:
        mysql:
          url: jdbc:mysql://${db.host}:${db.port:3306}/${db.name}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=UTC
          username: ${db.username}
          password: ${db.password}
          driver-class-name: ${digitforce.mysql.driver:com.mysql.cj.jdbc.Driver}
          hikari:
            # 最小空闲的连接数，Hikari默认10
            min-idle: ${digitforce.mysql.connection.min-idle:10}
            # 空闲连接存活最大时间，默认600000（10分钟）
            idle-timeout: 180000
            # 连接池最大连接数，Hikari默认10
            max-pool-size: ${digitforce.mysql.connection.max-active:100}
            # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
            is-auto-commit: true
            # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
            max-lifetime: 1800000
            # 数据库连接超时时间,默认30秒，即30000
            connection-timeout: 30000
            connection-test-query: SELECT 1
        olap:
          url: jdbc:mysql://${digitforce.olap.fe-addr}?failOverReadOnly=false
          username: ${digitforce.olap.username}
          password: ${digitforce.olap.password}
          driver-class-name: ${digitforce.olap.driver:com.mysql.cj.jdbc.Driver}
          hikari:
            # 最小空闲的连接数，Hikari默认10
            min-idle: ${digitforce.olap.connection.min-idle:10}
            # 空闲连接存活最大时间，默认600000（10分钟
            idle-timeout: 180000
            # 连接池最大连接数，Hikari默认10
            max-pool-size: ${digitforce.olap.connection.max-active:100}
            # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
            is-auto-commit: true
            # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
            max-lifetime: 1800000
            # 数据库连接超时时间,默认30秒，即30000
            connection-timeout: 30000
            connection-test-query: SELECT 1
  redis:
    cluster:
      nodes: ${redis.server-addr}
    password: ${redis.password}
    pool:
      max-active: ${redis.max-active:10}
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: dev-nacos-n1.digitforce.com:8848
  #        namespace: dev
  #        username: nacos
  #        password: nacos
  #    stream:
  #      bindings:
  #        eventInput:
  #          destination: mp-event-topic
  #          group: ${spring.application.name}
  #        maOutput:
  #          destination: ma-test-topic
  #          group: ${spring.application.name}
  #      rocketmq:
  #        binder:
  #          name-server: ${rocketmq.server-addr}
  #          group: ${spring.application.name}
  kafka:
    consumer:
      group-id: solution
      # TODO 后续将优化为group
      auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
digitforce:
  swagger:
    #项目信息（必填）
    version: 1.0.0
    title: ${rootArtifactId}
    description: ${rootArtifactId}开发文档
    #联系信息（选填）
    contactName: wangtonggui
    contactEmail: wangtonggui@digitforce.com
server:
  port: 7030
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      where-strategy: not_empty