logging:
  config: classpath:log4j2-spring-@profileActive@.xml
  file:
    path: .
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ${rootArtifactId}
  profiles:
    active: @profileActive@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${db.host}:${db.port:3306}/${db.name}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=UTC
    username: ${db.username}
    password: ${db.password}
    hikari:
      maximum-pool-size: ${db.max-active:10}
  redis:
    cluster:
      nodes: ${redis.server-addr}
    password: ${redis.password}
    pool:
      max-active: ${redis.max-active:10}
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: dev-nacos-n1.digitforce.com:8848
  #        namespace: dev
  #        username: nacos
  #        password: nacos
  #    stream:
  #      bindings:
  #        eventInput:
  #          destination: mp-event-topic
  #          group: ${spring.application.name}
  #        maOutput:
  #          destination: ma-test-topic
  #          group: ${spring.application.name}
  #      rocketmq:
  #        binder:
  #          name-server: ${rocketmq.server-addr}
  #          group: ${spring.application.name}
  kafka:
    consumer:
      group-id: solution
      # TODO 后续将优化为group
      auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
digitforce:
  swagger:
    #项目信息（必填）
    version: 1.0.0
    title: ${rootArtifactId}
    description: ${rootArtifactId}开发文档
    #联系信息（选填）
    contactName: wangtonggui
    contactEmail: wangtonggui@digitforce.com
server:
  port: 7030
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      where-strategy: not_empty